title: Tabern√°culo Puerta Abierta
description: Sitio oficial
baseurl: ""
url: ""

markdown: kramdown
theme: minima

# Keep Jekyll defaults for posts
permalink: /:categories/:year/:month/:day/:title/

# OPTIONAL: if you use plugins later, add them here
# plugins:
#   - jekyll-feed
